### ISSUE TITLE
prediction fails if input image has spaces in its name

### ISSUE THREAD

**Issue by anotherjesse** [lucataco/cog-seine#2]

**Comment by anotherjesse** [comment]
Or perhaps it is pngs?

https://replicate.com/p/3pobharblf5tknu4bfpald3g5i

**Comment by lucataco** [comment]
Thats odd, the [3 demo examples](https://replicate.com/lucataco/seine/examples) are using pngs

**Comment by lucataco** [comment]
Converted all input images to RGB for now
